export const NavItems = [
    {
        id:1,
        name:"Account",
        fields:[
            {
                id:1,
                name:"Profile",
            },
            {
                id:2,
                name:"Orders",
            },
            {
                id:3,
                name:"Help",
            },
        ],
    },
    {
        id:2,
        name:"Home",
        fields:[
            {
                id:1,
                name:"Best Selling Products",
            },
            {
                id:2,
                name:"Best Selling Services",
            },
            {
                id:3,
                name:"New Launches",
            },
        ],
    },
    {
        id:3,
        name:"Products",
        fields:[
            {
                id:1,
                name:"Smartphones",
            },
            {
                id:2,
                name:"Utensils",
            },
        ]
    },
    {
        id:4,
        name:"Services",
        fields:[
            {
                id:1,
                name:"Smartphones",
            },
            {
                id:2,
                name:"Utensils",
            },
        ]
    },
];